### PR TITLE
Fixes the imports so it gets the correct files on React NAtive and React Native Web.

### LINKED ISSUE #30: Fail callback not called when location permission denied
## Environment
```
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
      Memory: 269.32 MB / 32.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.0 - /usr/local/bin/node
      Yarn: 1.12.3 - ~/.npm-packages/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 23.0.2, 23.0.3, 25.0.0, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 27.0.1, 27.0.3, 28.0.3
        System Images: android-25 | Google APIs ARM 64 v8a, android-25 | Google APIs ARM EABI v7a, android-25 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.1 => 0.59.1 
```

## Platforms
Android

## Versions
- Android: 9
- react-native-geolocation: 1.4.0
- react-native: 0.59.1 => 0.59.1 
- react: 16.8.3 => 16.8.3 

## Description
Using `Geolocation.getCurrentPosition` on Android, when the user selects 'deny' when asked for permission to access the device's location, the fail callback is never called:

## Reproducible Demo
```
const getCurrentPosition = () => {
  return new Promise((resolve, reject) => {
    Geolocation.getCurrentPosition(
      ({ coords }) => {
        const { latitude, longitude } = coords;
        resolve({ latitude, longitude });
      },
      err => {
        console.log(err);
        reject(err);
      },
      {
        enableHighAccuracy: false,
        timeout: 3000
      }
    );
  });
};

getCurrentPosition();
```

### LINKED ISSUE #31: The module is imported incorrectly
## Environment
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.8 => 0.59.8
    npmGlobalPackages:
      eslint-plugin-react-native: 3.2.1
      react-native-cli: 2.0.1

## Platforms
Android and iOS

## Versions
- react-native-geolocation: 1.4.0
- react-native: 0.59.8

## Description
    import Geolocation from '@react-native-community/geolocation' 

imports the index.js instead of index.native.js, resulting in "method not supported by the browser" errors even on Android and iOS devices

### PR DESCRIPTION
**Pull request by matt-oakes**
This issue was because the `react-native` line in `package.json` was pointing to the "web" file so it would give errors. 

The fix to to have a single `index.js` which both platforms use and an `implementation.js` and `implementation.web.js` which allows the platform to pick the correct one.

# Test Plan
Tests should pass.

@NoemiRozpara or @michalchudziak: Can you check this works correctly for web?

Fixes #30
Fixes #31

### CODE REVIEW

**Comment by matt-oakes** [comment]
@michalchudziak I assume most users will be using this with standard React Native, so I would rather publish this with that as the "default" and Web being the secondary implementation. I think that holds less "risk" but also makes the code clearer as the plain `.js` file is not full of "not implemented" errors.

**Comment by matt-oakes** [comment]
@michalchudziak I've just re-read the arguments in the original PR about Webpack needing additional configuration to enable the `.web.js` file support. In that case, you're right that it should be that way around. Updating the PR now.

**Comment by janicduplessis** [comment]
An alternative way to get this working is using `js/index.native.js` or `js/index` for the `"react-native"` field in package.json. Looks like specifying the file extension bypasses the .native extension resolution.

**Comment by matt-oakes** [comment]
@janicduplessis Would that lead to React Native Web correctly picking up the `index.js` and React Native picking up `index.native.js`? Have you tested this as I don't use RNW and don't really know the details of how Metro and Webpack handle these cases?

**Comment by janicduplessis** [comment]
I assume webpack doesn't use the `"react-native"` field in package.json but I haven't tested.

**Comment by janicduplessis** [comment]
@matt-oakes Do you want to merge this as is for now just so we unbreak the latest version on npm?

**Comment by matt-oakes** [comment]
@janicduplessis Sure. It seems like this was confirmed to work. If you have a better solution then please send over a PR 👍

**Pull request merged**
